apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-brineyseq-nextseq2k
spec:
  capacity:
    storage: 70Ti
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-brineyseq-hdd
  nfs:
    server: brineyseq.scripps.edu
    path: "/volume1/VH00124/runs/run_data"