apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stringer-shared
spec:
  capacity:
    storage: 200Ti
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-stringer-hdd
  nfs:
    server: stringer.scripps.edu
    path: "/volume1/brineylab_shared"
