# propjoe-sc.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-propjoe-hdd
provisioner: nfs.csi.k8s.io
# parameters:
#   server: stringer.scripps.edu
#   share: /nfs_share
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
