apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-propjoe-shared
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-propjoe-hdd
  volumeName: nfs-propjoe-shared
  resources:
    requests:
      storage: 900Ti
