apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stringer-novaseq6k
spec:
  capacity:
    storage: 70Ti
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-stringer-hdd
  nfs:
    server: stringer.scripps.edu
    path: "/volume1/A01255/runs/run_data"
