apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stringer-nextseq2k
spec:
  capacity:
    storage: 200Ti
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-stringer-hdd
  nfs:
    server: brineyseq.scripps.edu
    path: "/volume1/VH00124/runs/run_data"
